# Generated by Django 5.1.4 on 2025-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='shax',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
