# Generated by Django 5.1.4 on 2025-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_popular_shax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avesome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('data', models.IntegerField(max_length=10)),
                ('nomber', models.IntegerField(max_length=50)),
                ('kal', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=50)),
            ],
        ),
    ]
