# Generated by Django 5.1.4 on 2025-02-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aur_alter_about_img_alter_about_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='offfer3',
            new_name='offer3',
        ),
    ]
