# Generated by Django 5.1.4 on 2025-02-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_offfer3_about_offer3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(max_length=5000)),
                ('send', models.CharField(max_length=10)),
                ('teks', models.TextField(max_length=100)),
            ],
        ),
    ]
